{
    'name': 'IM Helpdesk',
    'version': '1.0',
    'category': 'Services/Helpdesk',
    'sequence': 110,
    'summary': 'Quản lý ticket hỗ trợ khách hàng',
    'description': 'Helpdesk cho Odoo 19 Community.',
    'author': 'IM',
    'license': 'LGPL-3',
    'depends': ['base_setup', 'mail', 'utm', 'rating', 'resource', 'portal'],
    'data': [
        'security/helpdesk_security.xml',
        'security/ir.model.access.csv',
        'data/mail_message_subtype_data.xml',
        'data/mail_template_data.xml',
        'data/helpdesk_data.xml',
        'data/ir_cron_data.xml',
        'data/ir_sequence_data.xml',
        'views/helpdesk_ticket_views.xml',
        'report/helpdesk_ticket_analysis_views.xml',
        'report/helpdesk_sla_report_analysis_views.xml',
        'views/helpdesk_tag_views.xml',
        'views/helpdesk_tag_assignment_views.xml',
        'views/helpdesk_stage_views.xml',
        'views/helpdesk_sla_views.xml',
        'views/helpdesk_team_views.xml',
        'views/helpdesk_portal_templates.xml',
        'views/rating_rating_views.xml',
        'views/res_partner_views.xml',
        'views/mail_activity_views.xml',
        'views/helpdesk_templates.xml',
        'views/helpdesk_menus.xml',
        'wizard/helpdesk_stage_delete_views.xml',
    ],
    'post_init_hook': '_create_helpdesk_team',
    'installable': True,
    'application': True,
}
