{
    'name': 'IM Purchase Request',
    'version': '19.0.2.11.0',
    'category': 'Inventory/Purchase',
    'sequence': 115,
    'summary': 'Đề nghị mua hàng nội bộ, duyệt nhiều cấp theo hạn mức',
    'description': 'Phiếu đề nghị mua hàng đứng trước đơn mua của Odoo.',
    'author': 'IM',
    'license': 'LGPL-3',
    'depends': ['purchase', 'account', 'hr'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/ir_config_parameter_data.xml',
        'data/approval_level_data.xml',
        'data/config_data.xml',
        'wizard/refuse_wizard_views.xml',
        'wizard/overrun_wizard_views.xml',
        'views/purchase_request_views.xml',
        'views/approval_level_views.xml',
        'views/purchase_request_permission_views.xml',
        'views/purchase_request_config_views.xml',
        'views/purchase_order_views.xml',
        'views/account_move_views.xml',
        'views/menus.xml',
        'report/report_request.xml',
    ],
    'installable': True,
    'application': True,
}
