{
    'name': 'IM eLearning',
    'version': '19.0.2.0.0',
    'category': 'Website/eLearning',
    'sequence': 105,
    'summary': 'Video tự host, chứng chỉ tra cứu, chặn thi sớm, giao khoá',
    'description': 'Mở rộng website_slides cho đào tạo nội bộ doanh nghiệp.',
    'author': 'IM',
    'license': 'LGPL-3',
    'depends': [
        'website_slides',
        'website_slides_survey',
        'survey',
        'hr',
        'hr_skills',
    ],
    'data': [
        'security/im_elearning_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/hr_resume_data.xml',
        'data/slide_channel_tag_data.xml',
        'data/ir_cron_data.xml',
        'views/slide_slide_views.xml',
        'views/slide_channel_views.xml',
        'views/slide_certificate_views.xml',
        'views/slide_link_import_views.xml',
        'views/slide_move_section_views.xml',
        'views/course_assignment_views.xml',
        'views/templates_certificate_verify.xml',
        'views/website_slides_templates.xml',
        'views/menu_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'im_elearning/static/src/js/video_upload.js',
            'im_elearning/static/src/js/video_upload_field.js',
            'im_elearning/static/src/xml/video_upload_field.xml',
        ],
        'web.assets_tests': [
            'im_elearning/static/tests/tours/*.js',
        ],
        'web.assets_frontend': [
            'im_elearning/static/src/js/video_upload.js',
            'im_elearning/static/src/js/local_video_player.js',
            'im_elearning/static/src/js/multi_file_upload.js',
            'im_elearning/static/src/xml/multi_file_upload.xml',
            'im_elearning/static/src/xml/local_video.xml',
            'im_elearning/static/src/scss/im_elearning.scss',
        ],
    },
    'installable': True,
    'application': True,
}
